name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn add -D eslint && yarn add -D stylelint

      - name: Run Linters
        run: yarn lint:ts & yarn lint:css
